global:
  resolve_timeout: 5m

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'  # Replace with your Slack webhook
        channel: '#alerts'

route:
  receiver: 'slack-notifications'
